create Companise, CompaniseImgs model
wecode-bootcamp-korea/weWanted_u-backend pull request #1
Opened 2019-10-31 11:13 UTC by lordmyshepherd

은우님, 지훈님, 예리님 감사합니다.

2019-10-31 11:27 UTC, rampart81 requested changes
`parser.py` 파일 해당 브랜치에서 빼주세요

2019-10-31 11:27 UTC, rampart81 commented on company/models.py
> +        db_table = "companiseImgs"
`companiseImgs` ==> `companise_images`

2019-10-31 11:27 UTC, rampart81 commented on parser.py
> +    print(jobs_url_list)
print 삭제 해주세요

2019-10-31 11:27 UTC, rampart81 commented on parser.py
> +    #print(data_detail['job']['company']['name'])
주석 지워주세요

2019-10-31 11:27 UTC, rampart81 commented on parser.py
> +
빈칸 다 지워주세요

2019-10-31 11:27 UTC, rampart81 commented on parser.py
> +
스페이스 한 줄로 줄여주세요

2019-11-01 04:21 UTC, rampart81 requested changes

2019-11-01 04:21 UTC, rampart81 commented on company/models.py
> +    city            = models.CharField(max_length = 100)
위의 image 들은 URL 인가요?
URLField 사용하면 편합니다:

https://docs.djangoproject.com/en/2.2/ref/models/fields/#urlfield

2019-11-01 04:21 UTC, rampart81 commented on company/models.py
> +
아직도 아래 무의미한 스페이스 들이 있어요

2019-11-01 07:39 UTC, lordmyshepherd commented on company/models.py
> +
꼼꼼히 다시 확인하겠습니다.

2019-11-01 07:49 UTC, merged